name: Run a python version
inputs:
  py:
    description: Version of Python to use for this test
    type: string
runs:
  using: composite
  steps:
    - name: Install Python version
      uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.py }}
    - name: Run test script
      shell: bash
      run: |-
        python --version
        python single_test_run.py
